package org.fit.vutbr.relaxdms.custom;

import java.util.List;
import org.fit.vutbr.relaxdms.data.db.dao.model.workflow.Environment;
import org.fit.vutbr.relaxdms.data.db.dao.model.Document;
import org.fit.vutbr.relaxdms.data.db.dao.model.workflow.Workflow;
import org.fit.vutbr.relaxdms.data.db.dao.model.workflow.State;
import org.fit.vutbr.relaxdms.data.db.dao.model.workflow.ApprovalEnum;
import org.fit.vutbr.relaxdms.data.db.dao.model.workflow.StateEnum;
import org.fit.vutbr.relaxdms.data.db.dao.model.workflow.LabelEnum;
import org.fit.vutbr.relaxdms.data.db.dao.model.workflow.Label;

dialect "java"

rule "CustomWorkflow"
    when
        $env : Environment(isTrue() == true, getRule() == "CustomWorkflow", $fireBy : getFireBy())
    then
        modify($env) {
            setValue(false)
        };
        System.out.println("CustomWorkflow rule fired");
end

rule "AssignDocuments"
    when
        $env : Environment(isTrue(), getRule() == "AssignDocuments")
        $document : Document(workflow.assignment.assignee == "Unassigned"  &&
            workflow.state.currentState == StateEnum.OPEN)
    then
        String author = $document.getMetadata().getAuthor();
        modify($document) {
            getWorkflow().getAssignment().setAssignee(author)
        };
        docSet.add($document);
        System.out.println("AssignDocuments rule fired");
end